- name: Install SSH
  package:
    name: openssh-server
    state: latest

- name: Remove root SSH access
  notify: 
  - restart ssh
  lineinfile: 
    dest: /etc/ssh/sshd_config 
    regexp: "^PermitRootLogin" 
    line: "PermitRootLogin no" 
    state: present
