---
- name: "reload systemd"
  ansible.builtin.systemd_service:
    state: restarted
    daemon_reload: true

- name: "restart fail2ban"
  service: 
    name: "fail2ban"
    state: "restarted"
    enabled: "yes"
