---
- name: "Restart nft service"
  listen: "restart nft"
  ansible.builtin.command: "/etc/nftables.conf"
  changed_when: false

- name: "Reload rsyslog"
  listen: "restart rsyslog"
  ansible.builtin.service:
    name: "rsyslog"
    state: "restarted"
