- name: Install Fail2Ban
  package: name=fail2ban state=latest

- name: Install local config
  template:
    src: "etc/fail2ban/{{ item }}.j2"
    dest: "/etc/fail2ban/{{ item }}"
    owner: "root"
    group: "root"
    mode: "0400"

  with_items:
    - jail.d/omeganet.conf
  notify: restart fail2ban
