---
- name: "Systemd Daemon Reload"
  listen: "systemd daemon-reload"
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: "Restart Traefik"
  listen: "restart traefik"
  vars:
    service_name: "traefik.service"
  ansible.builtin.include_tasks:
    file: "tasks/check_reload.yml"
